### ISSUE TITLE
Cannot open file: nimpcre/pcre

### ISSUE THREAD

**Issue by 747** [genotrance/nimpcre#1]
`nimpcre` directory is empty after install.

- Windows 10  
`C:\Users\747\.nimble\pkgs\nimpcre-0.1.4\nimpcre.nim(1, 16) Error: cannot open file: nimpcre/pcre`
- Ubuntu 18.04 (WSL)  
`/home/747/.nimble/pkgs/nimpcre-0.1.4/nimpcre.nim(1, 16) Error: cannot open file: nimpcre/pcre`

With `compiler@0.20.0`, at first the dependency `c2nim` aborts because of a deprecated grammar, but this has fortunately been fixed an hour ago nim-lang/c2nim#155, then I could install this package. I'm not sure if the issue is related to the fix. Using `compiler@0.19.6` and/or `nimpcre@0.1.3` didn't change the situation either.

**Comment by genotrance** [comment]
Nimble doesn't run the before install step due to an issue.

Clone locally, run nimble setup then nimble install. 

I'll be changing this into a nimterop package soon.

**Comment by 747** [comment]
I see, thank you.

**Comment by genotrance** [comment]
This should now be fixed.
